services:
  flask-app-isak-landing:
    container_name: flask-app-isak-landing
    restart: always
    env_file: .env
    build: .
    ports:
      - "5006:5006"
    networks:
      - web_network

  nginx-isak-landing:
    container_name: nginx-isak-landing
    restart: always
    image: nginx:latest
    ports:
      - "40002:40002"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - flask-app-isak-landing


  dashboard-db:
    image: postgres:latest
    container_name: dashboard-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P4cQVW6aLQYYr4bJtZjZq
      POSTGRES_DB: IsakLandingDB
    volumes:
      - dashboard-postgres-data:/var/lib/postgresql/data
    ports:
      - "5437:5437"  # host:container
    command: postgres -p 5437
    restart: always

volumes:
  dashboard-postgres-data:


networks:
  web_network:
    driver: bridge
