services:
  flask-app-isak-landing:
    container_name: flask-app-isak-landing
    restart: always
    env_file: .env
    build: .
    ports:
      - "5006:5006"
    networks:
      - web_network

    environment:
      - PYTHONBUFFERED=1

    depends_on:
      - dashboard-db

  nginx-isak-landing:
    container_name: nginx-isak-landing
    restart: always
    image: nginx:latest
    ports:
      - "40002:40002"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - flask-app-isak-landing
      - dashboard-db


  dashboard-db:
    image: postgres:latest
    container_name: dashboard-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P4cQVW6aLQYYr4bJtZjZq
      POSTGRES_DB: IsakLandingDB
    volumes:
      - dashboard-postgres-data:/var/lib/postgresql/data
    ports:
      - "5437:5437"  # host:container

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d IsakLandingDB -p 5437" ]
      interval: 5s
      timeout: 5s
      retries: 12

    command: postgres -p 5437
    restart: always
    networks:
      - web_network


  wordlist-seed:
    build: .
    env_file:
      - .env
    environment:
      FLASK_APP: app:create_app
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      dashboard-db:
        condition: service_healthy
    networks:
      - web_network
    command: >
      sh -c "python -c 'from app import create_app; app=create_app(); from apps.security.seed_wordlists import seed_wordlists; ctx=app.app_context(); ctx.push(); seed_wordlists(); print(\"âœ… wordlist seed done\")'"


volumes:
  dashboard-postgres-data:


networks:
  web_network:
    driver: bridge
